# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/2.8.12.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/2.8.12.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/local/Cellar/cmake/2.8.12.1/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/zhangzhao/wap

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/zhangzhao/wap

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/2.8.12.1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/2.8.12.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zhangzhao/wap/CMakeFiles /Users/zhangzhao/wap/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zhangzhao/wap/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mapTest

# Build rule for target.
mapTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mapTest
.PHONY : mapTest

# fast build rule for target.
mapTest/fast:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/build
.PHONY : mapTest/fast

HDEController.o: HDEController.cpp.o
.PHONY : HDEController.o

# target to build an object file
HDEController.cpp.o:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/HDEController.cpp.o
.PHONY : HDEController.cpp.o

HDEController.i: HDEController.cpp.i
.PHONY : HDEController.i

# target to preprocess a source file
HDEController.cpp.i:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/HDEController.cpp.i
.PHONY : HDEController.cpp.i

HDEController.s: HDEController.cpp.s
.PHONY : HDEController.s

# target to generate assembly for a file
HDEController.cpp.s:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/HDEController.cpp.s
.PHONY : HDEController.cpp.s

ImageSet.o: ImageSet.cpp.o
.PHONY : ImageSet.o

# target to build an object file
ImageSet.cpp.o:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/ImageSet.cpp.o
.PHONY : ImageSet.cpp.o

ImageSet.i: ImageSet.cpp.i
.PHONY : ImageSet.i

# target to preprocess a source file
ImageSet.cpp.i:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/ImageSet.cpp.i
.PHONY : ImageSet.cpp.i

ImageSet.s: ImageSet.cpp.s
.PHONY : ImageSet.s

# target to generate assembly for a file
ImageSet.cpp.s:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/ImageSet.cpp.s
.PHONY : ImageSet.cpp.s

ProbTableElement.o: ProbTableElement.cpp.o
.PHONY : ProbTableElement.o

# target to build an object file
ProbTableElement.cpp.o:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/ProbTableElement.cpp.o
.PHONY : ProbTableElement.cpp.o

ProbTableElement.i: ProbTableElement.cpp.i
.PHONY : ProbTableElement.i

# target to preprocess a source file
ProbTableElement.cpp.i:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/ProbTableElement.cpp.i
.PHONY : ProbTableElement.cpp.i

ProbTableElement.s: ProbTableElement.cpp.s
.PHONY : ProbTableElement.s

# target to generate assembly for a file
ProbTableElement.cpp.s:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/ProbTableElement.cpp.s
.PHONY : ProbTableElement.cpp.s

Step.o: Step.cpp.o
.PHONY : Step.o

# target to build an object file
Step.cpp.o:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/Step.cpp.o
.PHONY : Step.cpp.o

Step.i: Step.cpp.i
.PHONY : Step.i

# target to preprocess a source file
Step.cpp.i:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/Step.cpp.i
.PHONY : Step.cpp.i

Step.s: Step.cpp.s
.PHONY : Step.s

# target to generate assembly for a file
Step.cpp.s:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/Step.cpp.s
.PHONY : Step.cpp.s

Trilateration.o: Trilateration.cpp.o
.PHONY : Trilateration.o

# target to build an object file
Trilateration.cpp.o:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/Trilateration.cpp.o
.PHONY : Trilateration.cpp.o

Trilateration.i: Trilateration.cpp.i
.PHONY : Trilateration.i

# target to preprocess a source file
Trilateration.cpp.i:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/Trilateration.cpp.i
.PHONY : Trilateration.cpp.i

Trilateration.s: Trilateration.cpp.s
.PHONY : Trilateration.s

# target to generate assembly for a file
Trilateration.cpp.s:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/Trilateration.cpp.s
.PHONY : Trilateration.cpp.s

accessPoint.o: accessPoint.cpp.o
.PHONY : accessPoint.o

# target to build an object file
accessPoint.cpp.o:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/accessPoint.cpp.o
.PHONY : accessPoint.cpp.o

accessPoint.i: accessPoint.cpp.i
.PHONY : accessPoint.i

# target to preprocess a source file
accessPoint.cpp.i:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/accessPoint.cpp.i
.PHONY : accessPoint.cpp.i

accessPoint.s: accessPoint.cpp.s
.PHONY : accessPoint.s

# target to generate assembly for a file
accessPoint.cpp.s:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/accessPoint.cpp.s
.PHONY : accessPoint.cpp.s

apStatus.o: apStatus.cpp.o
.PHONY : apStatus.o

# target to build an object file
apStatus.cpp.o:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/apStatus.cpp.o
.PHONY : apStatus.cpp.o

apStatus.i: apStatus.cpp.i
.PHONY : apStatus.i

# target to preprocess a source file
apStatus.cpp.i:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/apStatus.cpp.i
.PHONY : apStatus.cpp.i

apStatus.s: apStatus.cpp.s
.PHONY : apStatus.s

# target to generate assembly for a file
apStatus.cpp.s:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/apStatus.cpp.s
.PHONY : apStatus.cpp.s

mapTest.o: mapTest.cpp.o
.PHONY : mapTest.o

# target to build an object file
mapTest.cpp.o:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/mapTest.cpp.o
.PHONY : mapTest.cpp.o

mapTest.i: mapTest.cpp.i
.PHONY : mapTest.i

# target to preprocess a source file
mapTest.cpp.i:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/mapTest.cpp.i
.PHONY : mapTest.cpp.i

mapTest.s: mapTest.cpp.s
.PHONY : mapTest.s

# target to generate assembly for a file
mapTest.cpp.s:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/mapTest.cpp.s
.PHONY : mapTest.cpp.s

particle.o: particle.cpp.o
.PHONY : particle.o

# target to build an object file
particle.cpp.o:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/particle.cpp.o
.PHONY : particle.cpp.o

particle.i: particle.cpp.i
.PHONY : particle.i

# target to preprocess a source file
particle.cpp.i:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/particle.cpp.i
.PHONY : particle.cpp.i

particle.s: particle.cpp.s
.PHONY : particle.s

# target to generate assembly for a file
particle.cpp.s:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/particle.cpp.s
.PHONY : particle.cpp.s

particlePosition.o: particlePosition.cpp.o
.PHONY : particlePosition.o

# target to build an object file
particlePosition.cpp.o:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/particlePosition.cpp.o
.PHONY : particlePosition.cpp.o

particlePosition.i: particlePosition.cpp.i
.PHONY : particlePosition.i

# target to preprocess a source file
particlePosition.cpp.i:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/particlePosition.cpp.i
.PHONY : particlePosition.cpp.i

particlePosition.s: particlePosition.cpp.s
.PHONY : particlePosition.s

# target to generate assembly for a file
particlePosition.cpp.s:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/particlePosition.cpp.s
.PHONY : particlePosition.cpp.s

pixel.o: pixel.cpp.o
.PHONY : pixel.o

# target to build an object file
pixel.cpp.o:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/pixel.cpp.o
.PHONY : pixel.cpp.o

pixel.i: pixel.cpp.i
.PHONY : pixel.i

# target to preprocess a source file
pixel.cpp.i:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/pixel.cpp.i
.PHONY : pixel.cpp.i

pixel.s: pixel.cpp.s
.PHONY : pixel.s

# target to generate assembly for a file
pixel.cpp.s:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/pixel.cpp.s
.PHONY : pixel.cpp.s

point.o: point.cpp.o
.PHONY : point.o

# target to build an object file
point.cpp.o:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/point.cpp.o
.PHONY : point.cpp.o

point.i: point.cpp.i
.PHONY : point.i

# target to preprocess a source file
point.cpp.i:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/point.cpp.i
.PHONY : point.cpp.i

point.s: point.cpp.s
.PHONY : point.s

# target to generate assembly for a file
point.cpp.s:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/point.cpp.s
.PHONY : point.cpp.s

room.o: room.cpp.o
.PHONY : room.o

# target to build an object file
room.cpp.o:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/room.cpp.o
.PHONY : room.cpp.o

room.i: room.cpp.i
.PHONY : room.i

# target to preprocess a source file
room.cpp.i:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/room.cpp.i
.PHONY : room.cpp.i

room.s: room.cpp.s
.PHONY : room.s

# target to generate assembly for a file
room.cpp.s:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/room.cpp.s
.PHONY : room.cpp.s

sensorData.o: sensorData.cpp.o
.PHONY : sensorData.o

# target to build an object file
sensorData.cpp.o:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/sensorData.cpp.o
.PHONY : sensorData.cpp.o

sensorData.i: sensorData.cpp.i
.PHONY : sensorData.i

# target to preprocess a source file
sensorData.cpp.i:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/sensorData.cpp.i
.PHONY : sensorData.cpp.i

sensorData.s: sensorData.cpp.s
.PHONY : sensorData.s

# target to generate assembly for a file
sensorData.cpp.s:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/sensorData.cpp.s
.PHONY : sensorData.cpp.s

wallElement.o: wallElement.cpp.o
.PHONY : wallElement.o

# target to build an object file
wallElement.cpp.o:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/wallElement.cpp.o
.PHONY : wallElement.cpp.o

wallElement.i: wallElement.cpp.i
.PHONY : wallElement.i

# target to preprocess a source file
wallElement.cpp.i:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/wallElement.cpp.i
.PHONY : wallElement.cpp.i

wallElement.s: wallElement.cpp.s
.PHONY : wallElement.s

# target to generate assembly for a file
wallElement.cpp.s:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/wallElement.cpp.s
.PHONY : wallElement.cpp.s

wifiVector.o: wifiVector.cpp.o
.PHONY : wifiVector.o

# target to build an object file
wifiVector.cpp.o:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/wifiVector.cpp.o
.PHONY : wifiVector.cpp.o

wifiVector.i: wifiVector.cpp.i
.PHONY : wifiVector.i

# target to preprocess a source file
wifiVector.cpp.i:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/wifiVector.cpp.i
.PHONY : wifiVector.cpp.i

wifiVector.s: wifiVector.cpp.s
.PHONY : wifiVector.s

# target to generate assembly for a file
wifiVector.cpp.s:
	$(MAKE) -f CMakeFiles/mapTest.dir/build.make CMakeFiles/mapTest.dir/wifiVector.cpp.s
.PHONY : wifiVector.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... mapTest"
	@echo "... rebuild_cache"
	@echo "... HDEController.o"
	@echo "... HDEController.i"
	@echo "... HDEController.s"
	@echo "... ImageSet.o"
	@echo "... ImageSet.i"
	@echo "... ImageSet.s"
	@echo "... ProbTableElement.o"
	@echo "... ProbTableElement.i"
	@echo "... ProbTableElement.s"
	@echo "... Step.o"
	@echo "... Step.i"
	@echo "... Step.s"
	@echo "... Trilateration.o"
	@echo "... Trilateration.i"
	@echo "... Trilateration.s"
	@echo "... accessPoint.o"
	@echo "... accessPoint.i"
	@echo "... accessPoint.s"
	@echo "... apStatus.o"
	@echo "... apStatus.i"
	@echo "... apStatus.s"
	@echo "... mapTest.o"
	@echo "... mapTest.i"
	@echo "... mapTest.s"
	@echo "... particle.o"
	@echo "... particle.i"
	@echo "... particle.s"
	@echo "... particlePosition.o"
	@echo "... particlePosition.i"
	@echo "... particlePosition.s"
	@echo "... pixel.o"
	@echo "... pixel.i"
	@echo "... pixel.s"
	@echo "... point.o"
	@echo "... point.i"
	@echo "... point.s"
	@echo "... room.o"
	@echo "... room.i"
	@echo "... room.s"
	@echo "... sensorData.o"
	@echo "... sensorData.i"
	@echo "... sensorData.s"
	@echo "... wallElement.o"
	@echo "... wallElement.i"
	@echo "... wallElement.s"
	@echo "... wifiVector.o"
	@echo "... wifiVector.i"
	@echo "... wifiVector.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

