# Generated by CMake, DO NOT EDIT
# Custom rules for ALL_BUILD
.SUFFIXES: 
all: \
	/Users/zhangzhao/Hecate/sources/mapTest/CMakeFiles/ALL_BUILD


/Users/zhangzhao/Hecate/sources/mapTest/CMakeFiles/ALL_BUILD: 
	echo ""
	echo Build\ all\ projects
