# Generated by CMake, DO NOT EDIT
# Custom rules for mapTest
.SUFFIXES: 
all: \
	mapTest_buildpart_0


mapTest_buildpart_0: 
	echo "Depend check for xcode"
	cd /Users/zhangzhao/Hecate/sources/mapTest && make -C /Users/zhangzhao/Hecate/sources/mapTest -f /Users/zhangzhao/Hecate/sources/mapTest/CMakeScripts/XCODE_DEPEND_HELPER.make PostBuild.mapTest
