# Generated by CMake, DO NOT EDIT
# Custom rules for ZERO_CHECK
.SUFFIXES: 
all: \
	/Users/zhangzhao/Hecate/sources/mapTest/CMakeFiles/ZERO_CHECK


/Users/zhangzhao/Hecate/sources/mapTest/CMakeFiles/ZERO_CHECK: 
	echo ""
	make -f /Users/zhangzhao/Hecate/sources/mapTest/CMakeScripts/ReRunCMake.make
